### ISSUE TITLE
Will this work in a PHP and mySQL website?

### ISSUE THREAD

**Issue by nestsman** [rgl/MailBounceDetector#1]
I am happy to see something modern that is available for bounce processing.  Most products haven't been touched for years.  I didn't see anything in the readme file about PHP, so can you let me know?

Thank you.

**Comment by rgl** [comment]
I'm not sure I understood what you are looking for. This is just an C# library, it has nothing to do with PHP/MySQL. If you integrate it with an .NET application alongside your PHP app, sure, you can use this.

Also note that this only detects correctly formed bounce messages (e.g. from postfix/exchange/gmail) as described in the linked RFCs inside the README.md file. It does not yet handle bounces generated by qmail as described at [qsbmf.txt](http://cr.yp.to/proto/qsbmf.txt).
