### ISSUE TITLE
Support net45 or net451 profiles on NuGet packages

### ISSUE THREAD

**Issue by pruiz** [rgl/MailBounceDetector#2]
Hi,

I was interested in using this package, but it's NuGet package only provides binaries for net452 profile. Would you be willing to provide nuget packages supporting net45 or net451 profiles?

Regards
Pablo

**Comment by rgl** [comment]
I've targeted net45 on 05737483ae5a5f043bfd54e20f5eda804e94def2. It is available on nuget as version 1.0.3.
