### ISSUE TITLE
FileLoadException when using MailKit/MimeKit 1.16.1

### ISSUE THREAD

**Issue by cervengoc** [rgl/MailBounceDetector#9]
Hi, I get the following runtime exception when using the 1.0.3 NuGet version with MailKit/MimeKit 1.16.1.

```
FileLoadException - Could not load file or assembly 'MimeKit, Version=1.2.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

Could you please give some hints about this dependency issue?

**Comment by cervengoc** [comment]
Sorry, that was my mistake, I missed an appropriate binding redirect in my config file.

**Comment by liorafar** [comment]
Can you please explain what exactly you did to solve it?
Thanks

**Comment by MagicJohnJang** [comment]
I wanna know the detail too, met the same issue.

**Comment by MagicJohnJang** [comment]
I got it fixed!
In my case, code on two project but MailKit version not the same.  
Fixed it by Nuget update the MailKit version to the same between all projects.
